version: "24.0.7"

services:
  mysql:
    container_name: mysql-container
    image: mysql:8.0.36
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=preorder
      - MYSQL_USER=root
      - MYSQL_PASSWORD=1234
      - MYSQL_ROOT_PASSWORD=1234
