version: "24.0.7"

services:
  mysql:
    container_name: preorder-db
    image: mysql:8.0.31
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=preorder
      - MYSQL_ROOT_HOST=%
      - MYSQL_ROOT_PASSWORD=rootPassword
    volumes:
      - ./mysql/conf.d:/etc/mysql/conf.d
    command:
      - "mysqld"
      - "--character-set-server=utf8mb4"
      - "--collation-server=utf8mb4_unicode_ci"
    networks:
      - preorder-network

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - preorder-network

  preorder:
    container_name: preorder
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - preorder.env
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/preorder
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=rootPassword
      - SPRING_DATA_REDIS_HOST=redis
    restart: on-failure
    networks:
      - preorder-network
    stdin_open: true
    tty: true
    depends_on:
      - mysql
      - redis

networks:
  preorder-network:
    driver: bridge