version: "3.9"

services:
  user_service_db:
    container_name: user-db
    image: mysql:8.0.31
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=preorder
      - MYSQL_ROOT_HOST=%
      - MYSQL_ROOT_PASSWORD=rootPassword
    volumes:
      - ./mysql/conf.d:/etc/mysql/conf.d
    command:
      - "mysqld"
      - "--character-set-server=utf8mb4"
      - "--collation-server=utf8mb4_unicode_ci"
    networks:
      - preorder-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 5s
      retries: 5
      interval: 5s


  activity_service_db:
    container_name: activity-db
    image: mysql:8.0.31
    ports:
      - "3307:3306"
    environment:
      - MYSQL_DATABASE=preorder
      - MYSQL_ROOT_HOST=%
      - MYSQL_ROOT_PASSWORD=rootPassword
    volumes:
      - ./mysql/conf.d:/etc/mysql/conf.d
    command:
      - "mysqld"
      - "--character-set-server=utf8mb4"
      - "--collation-server=utf8mb4_unicode_ci"
    networks:
      - preorder-network
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      timeout: 5s
      retries: 5
      interval: 5s

  news_feed_service_db:
    container_name: news_feed-db
    image: mysql:8.0.31
    ports:
      - "3308:3306"
    environment:
      - MYSQL_DATABASE=preorder
      - MYSQL_ROOT_HOST=%
      - MYSQL_ROOT_PASSWORD=rootPassword
    volumes:
      - ./mysql/conf.d:/etc/mysql/conf.d
    command:
      - "mysqld"
      - "--character-set-server=utf8mb4"
      - "--collation-server=utf8mb4_unicode_ci"
    networks:
      - preorder-network
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      timeout: 5s
      retries: 5
      interval: 5s

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - preorder-network

  user_service:
    container_name: userService
    build:
      context: ./
      dockerfile: UserServiceDockerfile
    ports:
      - "8080:8080"
    env_file:
      - preorder.env
    environment:
      - SPRING_DATASOURCE_DRIVER-CLASS-NAME=com.mysql.cj.jdbc.Driver
      - SPRING_DATASOURCE_URL=jdbc:mysql://user_service_db:3306/preorder
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=rootPassword
      - SPRING_DATA_REDIS_HOST=redis
    networks:
      - preorder-network
    depends_on:
      user_service_db:
        condition: service_healthy

  activity_service:
    container_name: activityService
    build:
      context: ./
      dockerfile: ActivityServiceDockerfile
    ports:
      - "8081:8081"
    env_file:
      - preorder.env
    environment:
      - SPRING_DATASOURCE_DRIVER-CLASS-NAME=com.mysql.cj.jdbc.Driver
      - SPRING_DATASOURCE_URL=jdbc:mysql://activity_service_db:3306/preorder
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=rootPassword
      - SPRING_DATA_REDIS_HOST=redis
    networks:
      - preorder-network
    depends_on:
      activity_service_db:
        condition: service_healthy

  news_feed_service:
    container_name: newsFeedService
    build:
      context: ./
      dockerfile: NewsFeedServiceDockerfile
    ports:
      - "8082:8082"
    env_file:
      - preorder.env
    environment:
      - SPRING_DATASOURCE_DRIVER-CLASS-NAME=com.mysql.cj.jdbc.Driver
      - SPRING_DATASOURCE_URL=jdbc:mysql://news_feed_service_db:3306/preorder
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=rootPassword
      - SPRING_DATA_REDIS_HOST=redis
    networks:
      - preorder-network
    depends_on:
      news_feed_service_db:
        condition: service_healthy

networks:
  preorder-network:
    driver: bridge